url: https://y7kim.github.io
baseurl: thaisoshiro.github.io

# Site settings
title: Thais Oshiro
email: thaismayumioshiro@gmail.com
description: "I am Thais Oshiro. I love create new mobile applications for Android and mainly for iOS platforms! I also have great interesting in Machine Learning and Image Processing."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Thais Oshiro
  pic: 1
  position: Software Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Postal address (add as many lines as necessary)
address:
  - line: Brazil

# Build settings
markdown: kramdown
permalink: pretty

github: thaisoshiro.github.io



